### ISSUE TITLE
Please add a "download agent" option

### ISSUE THREAD

**Issue by contrast-jenn** [jharper-sec/c6t#3]
Hello c6 creator,

I think a great option may be to also pull down the Contrast agent, you can get it with a curl to https://download.java.contrastsecurity.com/latest.  Later it may make some sense to add an option to specify version, but that would be very helpful!

**Comment by jharper-sec** [comment]
- [ ] Update the Command Line Interface: Add a new command or option to the CLI for downloading the Contrast agent.
    - c6t download-agent
- [ ] Implement the Download Functionality: Create a function that will download the agent from the provided URL and save it to the desired location. There should be a default location and an optional flag to allow user to specify the download location.
    - c6t download-agent --file <path_to_file>
- [ ] Handle Version Specification: Optionally, add a parameter to specify the version of the agent to download.
    - c6t download-agent --version 6.3.0
